### ISSUE TITLE
Vector spaces

### ISSUE THREAD

**Issue by aepsil0n** [brendanzab/algebra#17]
These can be done, as soon as there are fields. Should also enable `nalgebra` to begin to migrate to the abstractions used here.

cc @sebcrozet

**Comment by WaDelma** [comment]
I have [started](https://github.com/WaDelma/algebra/tree/vector) on working to implement Module-like structures.

Do we need to have separate RightModule and LeftModule traits? And if we have those do we want Bimodule trait?

**Comment by WaDelma** [comment]
Should this be closed? Or is there still stuff the needs to be done?

**Comment by sebcrozet** [comment]
I think this can be closed. Other vector spaces (e.g. normed, finite, etc.) will be the topic of another issue.
