### ISSUE TITLE
Abstract operators out of structural traits

### ISSUE THREAD

**Issue by aepsil0n** [brendanzab/algebra#18]
There is a lot of code duplication for all the structural traits because all of them exist twice for addition and multiplication. The problem is also that one can not implement a magma, quasigroup, etc for any other operator than `+` or `*`. I would feel uncomfortable misusing these for, say, a wedge product. There are furthermore other built-in operators, for which it makes sense to implement these categories.

First I thought it might not be possible to do this to the type system, but then I tried and came up with a solution that allows us to actually be generic over the kind of operator. I haven't thought this through to the very end, but it looks like it works so far.

## Closed operators

First of all, let's find an abstraction over closed operators. 

```rust
/// A type closed under a binary operation
pub trait Closed<Op> {

    /// Apply the operator to two arguments
    fn op(&self, other: &Self) -> Self;
}
```

This trait provides a similar signature as the stdlib operators and it is generic over some type `Op`. Now what is `Op`? The simplest way to connect this trait to the language operators (or any other trait that qualifies) is to introduce a zero-sized struct for each and implement a concrete instance of this trait.

```rust
/// Addition
pub struct Addition;

impl<T> Closed<Addition> for T
    where T: Add<T, T>
{
    fn op(&self, other: &T) -> T {
        *self + *other
    }
}
```

This can be done analogously for all relevant operators and works nicely thanks to multidispatch. It can also be extended to arbitrary functions that can be used as an operator, e.g. a cross-product or a wedge product for differentials, etc.

The type parameter of the `Closed` trait can not be inferred, which makes for a bit of an ugly signature using this generically:

```rust
fn commute<T: Closed<Op>, Op>(a: &T, b: &T) -> T {
    b.op(a)
}

#[test]
fn int_ops_commute() {
    let (a, b) = (3i, 2i);
    assert_eq!(commute::<_, Addition>(&a, &b), a + b);
    assert_eq!(commute::<_, Multiplication>(&a, &b), a * b);
}
```

Note that one may define operators more generically in terms of right-hand side and result but I wanted to keep this example simple.

## Algebraic abstractions

Now this abstraction provides some benefits. For once we only need one generic definition for a Magma now instead of two and it automatically extends to all closed operators.

```rust
/// A magma
pub trait Magma<Op>: Closed<Op> + Eq {}

impl<T, Op> Magma<Op> for T
    where T: Closed<Op> + Eq
{}
```

Another nice feature is that we can do stuff with more operators at the same time. Enter the quasigroup, which has two separate notions of division.

```rust
/// Left divisible
pub trait LeftDivisible<Op>: Closed<Op> {}

/// A quasigroup
pub trait QuasiGroup<Mag, LeftDiv, RightDiv>:
    Magma<Mag>
    + LeftDivisible<LeftDiv>
    + Closed<RightDiv>
{ /* properties */ }
```

Currently, we can not write the following code due to rust-lang/rust#18693, which is why the above workaround using the helper trait is necessary. However, it was indicated that the restrictions here should be lifted in the future.

```rust
/// A quasigroup
/// NOTE: this does not compile at the moment!
pub trait QuasiGroup<Mag, LeftDiv, RightDiv>:
    Magma<Mag>
    + Closed<LeftDiv>
    + Closed<RightDiv>
{ /* properties */ }
```

**Comment by aepsil0n** [comment]
Just a quick link: there is an [interesting discussion on reddit](https://www.reddit.com/r/rust/comments/2srz0g/by_value_operator_overloading_problems/) mostly concerned with operator overloading. This is tangentially relevant, particularly how people perceive the ergonomics of certain APIs.

**Comment by bjz** [comment]
Thanks! By-ref vs by-val is a tricky problem.

**Comment by aepsil0n** [comment]
Just a quick remark: operator overloading semantics have changed a bit, so we should look into if and how this affects this issue. btw, has anybody thought about this (and maybe found a better solution than the parametric approach)?

**Comment by aepsil0n** [comment]
I have necro this discussion once again… I'm not seriously working on this any more, but [this article: "Scrap your typeclasses"](http://www.haskellforall.com/2012/05/scrap-your-type-classes.html) strongly reminded me of our issue here. Perhaps traits are not quite the right approach here altogether? Of course, Rust operators are backed by traits, which might make this trickier than it seems, but still I wonder, whether one could take a radically different approach here.

**Comment by WaDelma** [comment]
I found a way to [make](https://play.rust-lang.org/?gist=e96bceb37141e48ea3820dbd50f3ae6b) the calling for parametric approach somewhat cleaner.    
Instead of `Magma::<Additive>::op(a, b)` you can call it by `a.op(Additive, b)`.    
There is also a way to use this with generic `Magma`s via `Op` trait (Probably bad name for it.).
